### ISSUE TITLE
What does "all the wordlists under "Files" " mean?

### ISSUE THREAD

**Issue by ItsIgnacioPortal** [heinosasshallik/infosec-knowledge#1]
On https://github.com/heinosasshallik/infosec-knowledge/blob/master/wordlists/web_content/README.md

`  * common-words.txt (aka all the wordlists under "Files". Otherwise there would be no .git...)`

Where is the "Files" section supposed to be on SecLists?

**Comment by heinosasshallik** [comment]
I probably could have written it better, sorry. 

If you read the readme, then you can see this:

```
* Files:
  * common.txt
  * raft-small-words.txt
  * raft-small-words-lowercase.txt
  * raft-medium-words-lowercase.txt
  * raft-medium-words.txt
  * big.txt
  * raft-large-words-lowercase.txt
  * raft-large-words.txt          
```

The "Files" section isn't on SecLists. The Files section refers to the `combined_words` wordlist, which contains all the words I use for fuzzing files (I also add an extension, such as `.php`, `.txt`, etc).

I meant that the "Directories" wordlist (`combined_directories`) contains all the wordlists in the combined "Files" wordlist (`combined_words`).
